### ISSUE TITLE
Cloudflare 502 Bad Gateway

### ISSUE THREAD

**Issue by Higgs1** [neoascetic/rawgithack#78]
When attempting to access the URL https://bbcdn.githack.com/LexxyFox/std.js/raw/c2417eda/posix/errno.js I receive a 502 error from Cloudflare instead of the [expected content](https://bitbucket.org/LexxyFox/std.js/src/c2417eda/posix/errno.js). It's been like this for the past several days.

Also thank you for providing this service, it's been a valuable asset and I appreciate what you've done.

<sub><sup>Disclaimers: This disclaimer and the following text is written in English. The user generated content shown above is not written in English and thus cannot be interpreted as if it were written in English. In all circumstances, the user generated content above is a parody and intended only for entertainment purposes. The author of the content retains full, exclusive copyright. Using the content to train AI models is strictly forbidden, constitutes theft, and will be punished to the maximum extent possible.</sup></sub>

**Comment by neoascetic** [comment]
Hello!

The problem was with the headers size sent back by bitbucket — they didn't fit into nginx's buffers. I've increased the buffers size and now your URL works. 

And the status monitor didn't catch the issue (until yesterday) by some reason, probably bitbucket has some tricky logic regarding the headers behind the scene, i. e. it applies only to some repos.

Thanks for the report!

**Comment by Higgs1** [comment]
Thanks for the quick fix! I should have reported it days ago. And thanks again for GitHack! 

~4KiB is too many headers in my opinion.
